// Code generated by protoc-gen-go.
// source: github.com/hailocab/bakery-fcOIDQQhF6bEHSX8/proto/foo/foo.proto
// DO NOT EDIT!

/*
Package com_hailocab_service_bakery_foo is a generated protocol buffer package.

It is generated from these files:
	github.com/hailocab/bakery-fcOIDQQhF6bEHSX8/proto/foo/foo.proto

It has these top-level messages:
	Request
	Response
*/
package com_hailocab_service_bakery_foo

import proto "github.com/hailocab/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request struct {
	Bar              *string `protobuf:"bytes,1,req,name=bar" json:"bar,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetBar() string {
	if m != nil && m.Bar != nil {
		return *m.Bar
	}
	return ""
}

type Response struct {
	Baz              *string `protobuf:"bytes,1,req,name=baz" json:"baz,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetBaz() string {
	if m != nil && m.Baz != nil {
		return *m.Baz
	}
	return ""
}

func init() {
}
