language: go

go:
  - 1.5

before_install:
  - curl -LO https://releases.hashicorp.com/packer/0.8.6/packer_0.8.6_linux_amd64.zip
  - unzip packer_0.8.6_linux_amd64.zip
  - export PATH="$PWD/packer_0.8.6_linux_amd64:$PATH"

install:
  - echo ""

script:
  - go test -v $(go list ./... | grep -v /vendor/)
  - go build -o bakery-service
